version: '3.8'

services:
  vector-embedding:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - EMBEDDING_MODEL_OPENAI=text-embedding-3-small
      - EMBEDDING_MODEL_LOCAL=all-MiniLM-L6-v2
      - CACHE_TTL=86400
      - MAX_BATCH_SIZE=100
      - VECTOR_DIMENSION=1536
      - FAISS_INDEX_PATH=/app/data/faiss_index.bin
    volumes:
      - vector_data:/app/data
    depends_on:
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 3s
      retries: 3

volumes:
  vector_data:
    driver: local
  redis_data:
    driver: local