name: Auto Release on Tag

on:
  push:
    tags:
      - "v*"

jobs:
  sync-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      - name: Extract version from tag
        id: version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Sync website version
        run: |
          npm run sync-version
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add website/lib/version.ts
          git diff --cached --quiet || (git commit -m "chore: sync website version to ${{ steps.version.outputs.version }}" && git push origin HEAD:main)

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          body: |
            ## R3call v${{ steps.version.outputs.version }}

            Lightning-fast memory layer for AI applications with sub-5ms response times.

            ### Installation
            ```bash
            npm install r3call@${{ steps.version.outputs.version }}
            ```

            ### Claude Desktop Setup
            ```bash
            npx r3call
            ```

            ### Documentation
            - [Getting Started](https://r3call.newth.ai/docs/quickstart)
            - [API Reference](https://r3call.newth.ai/docs/api-reference)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
